on: [push]
jobs:
  build:
    runs-on: nix
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4.2.2
      - run: env
      - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#extension .#checks.x86_64-linux.my-app-fmt
