[package]
name = "tucan-injector"
license.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
wasm-bindgen = "0.2"
tucan-connector = { path = "../tucan-connector" }
web-sys = { version = "0.3", features = ["Document", "Window", "HtmlDocument"] }
cookie = "0.18"
url = "2"
console_log = { version = "1", features = ["color"] }
log = "0.4"

[lints]
workspace = true
