permissions:
  id-token: write
  attestations: write

name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install -f wasm-bindgen-cli --version 0.2.95
    - run: cargo build --target=wasm32-unknown-unknown
      working-directory: tucan-injector
    - run: wasm-bindgen --out-dir=wasm-bindgen ../target/wasm32-unknown-unknown/debug/tucan_injector.wasm
      working-directory: tucan-injector
    - run: npm install
      working-directory: tucan-injector
    - run: npm run build
      working-directory: tucan-injector
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: tucan-injector/dist/tucan-injector.js