permissions:
  id-token: write
  attestations: write

name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd tucan-injector
    - run: cargo build --verbose --target=wasm32-unknown-unknown
    - run: wasm-bindgen --out-dir=wasm-bindgen ../target/wasm32-unknown-unknown/debug/tucan_injector.wasm
    - run: npm run build
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: tucan-injector/dist/tucan-injector.js